### PR TITLE
PR to merge DBSClient4go branch into dmwm/main

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by yuyiguo** [comment]
I agreed, but too late.

**Comment by vkuznet** [comment]
@amaltaro , you are obviously late, sorry, I do not check regularly every single comment. But, this is a merge of the branch rather than individual PR with commits, as such history of the branch should be preserved. Since CLI and web tools were used (I merged my local branch to local main, then made PR to origin main branch), then use web UI to create PR, I'm unaware of web UI squash procedure. If you do please pass to me clear documented which I can use in a future. Finally, we have different views and habits about commits, and it is separate discussion about squashes (which I'm not in favor of as they hide mind set of developer and possible iterations of individual implementations).

**Comment by amaltaro** [comment]
@vkuznet here is a pretty good and simple documentation of this process that I have bookmarked for a long time:
https://steveklabnik.com/writing/how-to-squash-commits-in-a-github-pull-request

If you have questions, I am happy to help you out as well.

> Finally, we have different views and habits about commits, and it is separate discussion about squashes (which I'm not in favor of as they hide mind set of developer and possible iterations of individual implementations).

Which is expected and completely understandable. However, honestly, many of those commit messages are garbage and should never make it to the commit history. It makes things much harder when you have to check the history of a module as well. Pushing intermediate commits - with future meaningless information - only makes things less clear, IMO.

**Comment by yuyiguo** [comment]
I can not agree more with @amaltaro. Well said.

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, on the other hand, it might be worth it setting something explicitly in the repository as well. Otherwise developers don't really know which workflow to use and what the guidelines are ;-)

For this repository, I think it would be quite useful to have something like what we created for WMCore (which is in need of some updates TBF!):
https://github.com/dmwm/WMCore/blob/master/CONTRIBUTING.rst

**Comment by yuyiguo** [comment]
Thanks @Alan, will looked into this. Bookmarked the squash-commit link. It is quite simple one can do it to get a clean history.   I talked with Valentin about this before his commit, but I did not know the trick. Learnt it.

**Comment by vkuznet** [comment]
@amaltaro , please read carefully of what I wrote. I asked about documentation based on web UI, and not on CLI. For all CLI actions I do perform squash when asked (and try to adjust my habits), but I am not aware when you made PR on web interface how you can squash from the web these commits. If you do, as I wrote, please pass along the documentation.

Regarding different views, as I said, it is separate discussion, and for some developers "garbage" is truly valuable. If you want such discussion please answer few questions:
- how many times per year you do squash
- how many times per year you actually look back to github history
- how you can find what cause a change of certain squashed PR
- how can you figure out from squashed PR if final algorithm/block of code/etc. had different angle/implementation

As I said we have different habits and even though they overlap I do disagree with some. And, as I do adopt yours (e.g. making pylint, pep changes, squash individual commits) I hope you can at least consider my arguments too and try to understand them.

**Comment by amaltaro** [comment]
Ohh, web UI is completely different and I can't say, I never use it!
However, I think one could do something like:
```
git pull origin main
```
which would pull / checkout this branch, and then you could squash all the commits you want. But again, I am not sure it would work.

I do agree that sometimes an intermediate commit is valuable, and if that's the case, it should be kept for future reference. Sure, we can discuss it in a different venue.

**Pull request merged**
