### PR TITLE
Use >= instead of == in requirements to avoid python dependency conflcts

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
LGTM! Thanks Valentin.

**Comment by vkuznet** [comment]
@amaltaro should we merge it or should we switch to `~=`?

**Comment by amaltaro** [comment]
Giving it a second look, I think we should be precise on the version for `dbs3-pycurl`, thus using `==`. For `pycurl`, we better go with the compatible specifier `~=`. What do you think? Sorry for missing this in my previous review.

**Comment by vkuznet** [comment]
yes, I agree, I adjusted and squashed the changes.

**Review by amaltaro — APPROVED** [review]
Thanks Valentin. It looks great now!

**Pull request merged**
